language: clojure
lein: 2.8.1
sudo: false

script:
  - lein cloverage --codecov

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk10
  - oraclejdk8
  - oraclejdk7
  - openjdk11
  - openjdk10
  - openjdk8
  - openjdk7

after_success:
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
  - bash deploy
